services:
  - type: web
    name: api-users-render
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/Johan409IA/api-users-auth
    autoDeployTrigger: commit
    buildCommand: pnpm install && pnpm build
    preDeployCommand: pnpm prisma:deploy && pnpm seed
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://api-users-auth.onrender.com
      - key: SEED_ADMIN_EMAIL
        value: admin@example.com
      - key: SEED_ADMIN_PASSWORD
        generateValue: true
      - key: SEED_ADMIN_NAME
        value: Administrador
    healthCheckPath: /health

databases:
  - name: api-users-db
    databaseName: api_users
    user: api_users_user
    plan: free
    ipAllowList: []